/* 
 * Copyright (C) 2018 Calder Young. All Rights Reserved.
 *
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/ or send a letter to Creative
 * Commons, PO Box 1866, Mountain View, CA 94042, USA. 
 */

var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(k,x,D){if(k==Array.prototype||k==Object.prototype)return k;k[x]=D.value;return k};
$jscomp.getGlobal=function(k){k=["object"==typeof globalThis&&globalThis,k,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var x=0;x<k.length;++x){var D=k[x];if(D&&D.Math==Math)return D}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(k,x){var D=$jscomp.propertyToPolyfillSymbol[x];if(null==D)return k[x];D=k[D];return void 0!==D?D:k[x]};$jscomp.polyfill=function(k,x,D,t){x&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(k,x,D,t):$jscomp.polyfillUnisolated(k,x,D,t))};
$jscomp.polyfillUnisolated=function(k,x,D,t){D=$jscomp.global;k=k.split(".");for(t=0;t<k.length-1;t++){var V=k[t];if(!(V in D))return;D=D[V]}k=k[k.length-1];t=D[k];x=x(t);x!=t&&null!=x&&$jscomp.defineProperty(D,k,{configurable:!0,writable:!0,value:x})};
$jscomp.polyfillIsolated=function(k,x,D,t){var V=k.split(".");k=1===V.length;t=V[0];t=!k&&t in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var H=0;H<V.length-1;H++){var Ka=V[H];if(!(Ka in t))return;t=t[Ka]}V=V[V.length-1];D=$jscomp.IS_SYMBOL_NATIVE&&"es6"===D?t[V]:null;x=x(D);null!=x&&(k?$jscomp.defineProperty($jscomp.polyfills,V,{configurable:!0,writable:!0,value:x}):x!==D&&(void 0===$jscomp.propertyToPolyfillSymbol[V]&&(D=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[V]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(V):$jscomp.POLYFILL_PREFIX+D+"$"+V),$jscomp.defineProperty(t,$jscomp.propertyToPolyfillSymbol[V],{configurable:!0,writable:!0,value:x})))};$jscomp.underscoreProtoCanBeSet=function(){var k={a:!0},x={};try{return x.__proto__=k,x.a}catch(D){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(k,x){k.__proto__=x;if(k.__proto__!==x)throw new TypeError(k+" is not extensible");return k}:null;$jscomp.arrayIteratorImpl=function(k){var x=0;return function(){return x<k.length?{done:!1,value:k[x++]}:{done:!0}}};$jscomp.arrayIterator=function(k){return{next:$jscomp.arrayIteratorImpl(k)}};
$jscomp.makeIterator=function(k){var x="undefined"!=typeof Symbol&&Symbol.iterator&&k[Symbol.iterator];return x?x.call(k):$jscomp.arrayIterator(k)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(k){if(!(k instanceof Object))throw new TypeError("Iterator result "+k+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(k){this.yieldResult=k};$jscomp.generator.Context.prototype.throw_=function(k){this.abruptCompletion_={exception:k,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(k){this.abruptCompletion_={"return":k};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(k){this.abruptCompletion_={jumpTo:k};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(k,x){this.nextAddress=x;return{value:k}};$jscomp.generator.Context.prototype.yieldAll=function(k,x){var D=$jscomp.makeIterator(k),t=D.next();$jscomp.generator.ensureIteratorResultIsObject_(t);if(t.done)this.yieldResult=t.value,this.nextAddress=x;else return this.yieldAllIterator_=D,this.yield(t.value,x)};
$jscomp.generator.Context.prototype.jumpTo=function(k){this.nextAddress=k};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(k,x){this.catchAddress_=k;void 0!=x&&(this.finallyAddress_=x)};$jscomp.generator.Context.prototype.setFinallyBlock=function(k){this.catchAddress_=0;this.finallyAddress_=k||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(k,x){this.nextAddress=k;this.catchAddress_=x||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(k){this.catchAddress_=k||0;k=this.abruptCompletion_.exception;this.abruptCompletion_=null;return k};$jscomp.generator.Context.prototype.enterFinallyBlock=function(k,x,D){D?this.finallyContexts_[D]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=k||0;this.finallyAddress_=x||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(k,x){var D=this.finallyContexts_.splice(x||0)[0];if(D=this.abruptCompletion_=this.abruptCompletion_||D){if(D.isException)return this.jumpToErrorHandler_();void 0!=D.jumpTo&&this.finallyAddress_<D.jumpTo?(this.nextAddress=D.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=k};$jscomp.generator.Context.prototype.forIn=function(k){return new $jscomp.generator.Context.PropertyIterator(k)};
$jscomp.generator.Context.PropertyIterator=function(k){this.object_=k;this.properties_=[];for(var x in k)this.properties_.push(x);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var k=this.properties_.pop();if(k in this.object_)return k}return null};$jscomp.generator.Engine_=function(k){this.context_=new $jscomp.generator.Context;this.program_=k};
$jscomp.generator.Engine_.prototype.next_=function(k){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,k,this.context_.next_);this.context_.next_(k);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(k){this.context_.start_();var x=this.context_.yieldAllIterator_;if(x)return this.yieldAllStep_("return"in x?x["return"]:function(D){return{value:D,done:!0}},k,this.context_["return"]);this.context_["return"](k);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(k){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],k,this.context_.next_);this.context_.throw_(k);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(k,x,D){try{var t=k.call(this.context_.yieldAllIterator_,x);$jscomp.generator.ensureIteratorResultIsObject_(t);if(!t.done)return this.context_.stop_(),t;var V=t.value}catch(H){return this.context_.yieldAllIterator_=null,this.context_.throw_(H),this.nextStep_()}this.context_.yieldAllIterator_=null;D.call(this.context_,V);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var k=this.program_(this.context_);if(k)return this.context_.stop_(),{value:k.value,done:!1}}catch(x){this.context_.yieldResult=void 0,this.context_.throw_(x)}this.context_.stop_();if(this.context_.abruptCompletion_){k=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(k.isException)throw k.exception;return{value:k["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(k){this.next=function(x){return k.next_(x)};this["throw"]=function(x){return k.throw_(x)};this["return"]=function(x){return k.return_(x)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(k,x){var D=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(x));$jscomp.setPrototypeOf&&k.prototype&&$jscomp.setPrototypeOf(D,k.prototype);return D};
$jscomp.asyncExecutePromiseGenerator=function(k){function x(t){return k.next(t)}function D(t){return k["throw"](t)}return new Promise(function(t,V){function H(Ka){Ka.done?t(Ka.value):Promise.resolve(Ka.value).then(x,D).then(H,V)}H(k.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(k){return $jscomp.asyncExecutePromiseGenerator(k())};$jscomp.asyncExecutePromiseGeneratorProgram=function(k){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(k)))};
var DEBUG=!1,width=1280,height=720,aspect=16/9,updateRate=30,frameTime=1E3/updateRate;DEBUG&&window.addEventListener("error",function(k){alert("ERROR: "+k.message+"\n"+k.filename+":"+k.lineno+"e.colno");return!1});
window.addEventListener("load",function(){function k(){var a=window.innerWidth,f=a/aspect;f>window.innerHeight&&.87>window.innerHeight/f&&(f=window.innerHeight,a=f*aspect);a=Math.min(a,window.innerWidth);f=Math.min(f,window.innerHeight);ab=20>window.screen.width-a&&20>window.screen.height-f?!1:!0;document.fullscreenElement&&(ab=!1);sb.width=a;sb.height=f;tb.width=a;tb.height=f;Tb=a/width;Ub=f/height;C.setTransform(Tb,0,0,Ub,0,0);c.viewport(0,0,a,f);ub=(window.innerWidth-a)/2;vb=(window.innerHeight-
f)/2;(0<ub||0<vb)&&S();sb.style.top=vb+"px";sb.style.left=ub+"px";tb.style.top=vb+"px";tb.style.left=ub+"px"}function x(a){va=Math.floor((a.clientX-ub)/Tb);wa=Math.floor((a.clientY-vb)/Ub);0>va&&(va=0);0>wa&&(wa=0);va>width&&(va=width);wa>height&&(wa=height)}function D(){try{document.body.requestFullscreen()}catch(a){try{document.body.webkitRequestFullscreen()}catch(f){try{document.body.mozRequestFullscreen()}catch(r){}}}}function t(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){return f["return"](new Promise(function(r,
J){var g=new Image;g.onload=function(){var L=c.createTexture();c.bindTexture(c.TEXTURE_2D,L);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,g);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_S,c.CLAMP_TO_EDGE);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_T,c.CLAMP_TO_EDGE);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,c.LINEAR);r(L)};g.onerror=J;g.src=a}))})}function V(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){return f["return"](new Promise(function(r,
J){var g=new Image;g.onload=function(){return r(g)};g.onerror=J;g.src=a}))})}function H(a){var f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(r){f={buf:a,sync:0,retry:0};return r["return"](new Promise(function(J,g){Ka(f,function(L){L.buffer=hf;J(L)},function(L){g(L)})}))})}function Ka(a,f,r){Y.decodeAudioData(a.buf,f,function(J){var g;var L=new Uint8Array(a.buf);L.indexOf=Array.prototype.indexOf;for(g=a.sync;;){a.retry++;g=L.indexOf(255,g);if(-1==g||L[g+1]&1)break;g++}-1!=g?(L=a.buf.slice(g),
delete a.buf,a.buf=L,a.sync=g,g=!0):g=!1;g?Ka(a,f,r):r(J)})}function hf(){var a=Y.createBufferSource();bb.push(a);a.addEventListener("ended",function(){var f=bb.indexOf(a);-1!=f&&bb.splice(f,1)});a.buffer=this;return a}function ka(){for(var a=0;a<bb.length;a++)bb[a].stop();bb=[]}function A(a,f,r){a=a.buffer();r&&(a.loop=!0);a.connect(f);a.start()}function wb(){var a=n.scream.buffer();a.connect(l.main);a.start(0,.05)}function Dc(a,f,r,J){a=a.buffer();J&&(a.loop=!0);J=Y.createGain();a.connect(J);M(J,
f);J.connect(r);a.start()}function Vb(){c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,c.NEAREST)}function Ec(){c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,c.LINEAR)}function La(a,f){C.fillText(a,(1280-C.measureText(a).width)/2,f)}function vc(a,f,r){C.fillText(a,1280-C.measureText(a).width-f,r)}function jf(a,f,r,J){C.fillText(a,r+(f-C.measureText(a).width)/2,J)}function Fc(a,
f,r){C.fillText(f,(1280-C.measureText(a).width)/2,r)}function S(){return Date.now()}function xb(a,f){var r=c.createShader(a);c.shaderSource(r,f);c.compileShader(r);return c.getShaderParameter(r,c.COMPILE_STATUS)?r:(console.log("shader error: "+c.getShaderInfoLog(r)),c.deleteShader(r),null)}function Wb(a,f){var r=c.createProgram();c.attachShader(r,a);c.attachShader(r,f);c.linkProgram(r);return c.getProgramParameter(r,c.LINK_STATUS)?new Xb(r):(console.log("program error: "+c.getProgramInfoLog(r)),c.deleteProgram(r),
null)}function Xb(a){this.id=a;this.attributes={};this.uniforms={}}function B(a){c.bindBuffer(c.ARRAY_BUFFER,Hb);a.bind();d.exportTo(a);a=a.attributes.vert;c.vertexAttribPointer(a,2,c.FLOAT,!1,0,0);c.enableVertexAttribArray(a);c.drawArrays(c.TRIANGLES,0,6);c.disableVertexAttribArray(a)}function Yb(a){c.bindBuffer(c.ARRAY_BUFFER,Hb);ya.bind();c.uniform1f(ya.uniforms.alpha,a);d.exportTo(ya);a=ya.attributes.vert;c.vertexAttribPointer(a,2,c.FLOAT,!1,0,0);c.enableVertexAttribArray(a);c.drawArrays(c.TRIANGLES,
0,6);c.disableVertexAttribArray(a)}function Ib(a){c.bindBuffer(c.ARRAY_BUFFER,Hb);Ma.bind();c.uniform4fv(Ma.uniforms.color,a);d.exportTo(Ma);a=Ma.attributes.vert;c.vertexAttribPointer(a,2,c.FLOAT,!1,0,0);c.enableVertexAttribArray(a);c.drawArrays(c.TRIANGLES,0,6);c.disableVertexAttribArray(a)}function yb(a,f){if(a!=Zb||f!=$b)a!=Zb&&(c.uniform1f(G.uniforms.warp,a),DEBUG&&console.log("setting warp: "+a)),f!=$b&&(c.uniform1f(G.uniforms.heightfac,f),DEBUG&&console.log("setting heightfac: "+f)),Zb=a,$b=
f}function kf(){var a=!1,f=navigator.userAgent||navigator.vendor||window.opera;if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i.test(f)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(f.substr(0,
4)))a=!0;return a}function E(a,f,r,J){return zb?va>=a-cb&&va<=r+cb&&wa>=f-wc&&wa<=J+wc:va>=a&&va<=r&&wa>=f&&wa<=J}function w(a,f){return Math.floor(Math.random()*(f-a+1))+a}function lf(){R=0;xc=S();fa=da=!1;db=eb=0;za=W=!1;Aa=0;Na=!1;I=Va=0;ac=setTimeout(Gc,5E3);v=q=m=17;T=0;y=-1;Wa=Oa=Xa=Pa=0;xa=Ba=Ya=!1;1==Z?(ia=3,ea=2,ha=la=aa=0):2==Z?(ea=ia=6,aa=0,la=6,ha=0):3==Z?(ia=9,ea=11,aa=5,la=9,ha=0):4==Z?(ia=14,aa=ea=8,la=11,ha=5):5==Z?(ia=13,ea=14,la=aa=13,ha=8):6==Z?(la=aa=ea=ia=16,ha=12):7==Z?(ia=z.longarms,
ea=z.wierdclimber,aa=z.charles,la=z.laxdude,ha=z.winston,Ya=z.infinitepower,Ba=z.reducedstatic,xa=z.noaggression):8==Z&&(ha=la=aa=ea=ia=20,xa=Ba=Ya=!0);Ab=Bb=Jb=fb=!1;ma=0;bc=S();P=Z;cc=dc=ec=fc=X=0;Kb=S()+5E3;gc=2;Cb=0;hc=S();Qa=!1;gb=ic=0;qa=S();ra=sa=Ra=Q=Lb=0;Sa=999;Ca=!1;jc=S();hb=S();kc=S();Db=S();lc=S();oa=Mb=0;mc=S();M(l.ambience,.2);ba=0;ib=!1;Eb=!0;nc=S();Nb=0;if(1==oc||oc!=P)oc=P,Eb=!1,setTimeout(function(){M(l.call,1);A(n.call[P-1],l.call)},5E3)}function Hc(){clearTimeout(ac);ka();M(l.lights,
0);M(l.office,0);M(l.sstatic,0);M(l.camglitch,0)}function Ob(){A(n.title,l.main,!0);Dc(n.static2,.8,l.main)}function Gc(){var a=n.amb[w(0,2)];A(a,l.ambience);ac=setTimeout(Gc,Math.floor(1E3*a.duration))}function yc(){d.push();d.scale([1280,720]);c.bindTexture(c.TEXTURE_2D,b.sstatic.norm[jb%6]);B(O);d.pop()}function Ic(){d.push();d.scale([1280,720]);c.bindTexture(c.TEXTURE_2D,b.sstatic.heavyscan[jb%5]);Vb();B(O);d.pop()}function Da(a){if(W&&!Qa){a=zc[a];for(var f=S(),r=0;r<a.length;r++){var J=a[r];
Ea[a[r]]=0<f-Ea[J]&&I==J?Ba?f+w(100,200):f+w(5E3,9E3):Ba?f+w(50,100):f+w(1E3,2E3)}}}function M(a,f){a.gain.setValueAtTime(f,Y.currentTime)}function mf(){var a;if(!(a=parseInt(window.localStorage.getItem(Fa+"night")))||1>a||5<a||isNaN(a))1>a&&(a=1),5<a&&(a=5),isNaN(a)&&(a=1),window.localStorage.setItem(Fa+"night",a);return Pb=a}function Jc(a){window.localStorage.setItem(Fa+"night",a);Pb=a}function Kc(a){window.localStorage.setItem(Fa+"6th",a?"1":"0");kb=a}function Lc(a){window.localStorage.setItem(Fa+
"7th",a?"1":"0");lb=a}function Mc(a){window.localStorage.setItem(Fa+"20mode",a?"1":"0");Qb=a}function nf(){if(0==I)return 1==m&&0==v?b.cams[0].nl1c1:1==m&&1==v?b.cams[0].nl1c0:0==v?b.cams[0].nc0:1==v?b.cams[0].nc1:1==m?b.cams[0].nl1:b.cams[0].n;if(1==I)return 2==T?3==m&&2==v?b.cams[1].nl3c2d2:3==m?b.cams[1].nl3d2:2==v?b.cams[1].nc2d2:b.cams[1].nd2:3==T?3==m&&2==v?b.cams[1].nl3c2d3:3==m?b.cams[1].nl3d3:2==v?b.cams[1].nc2d3:3==q?b.cams[1].nw3d3:b.cams[1].nd3:4<=T?3==m&&2==v?b.cams[1].nl3c2d4:3==m?b.cams[1].nl3d4:
2==v?b.cams[1].nc2d4:b.cams[1].nd4:3==m&&3==q?b.cams[1].nl3w3:3==m&&2==v?b.cams[1].nl3c2:2==v?b.cams[1].nc2:3==m?b.cams[1].nl3:b.cams[1].n;if(2==I)return 1==T?3==m&&3==q?b.cams[2].nl3w3d1:3==m?b.cams[2].nl3d1:3==q?b.cams[2].nw3d1:b.cams[2].nd1:2==T?3==m?b.cams[2].nl3d2:3==q?b.cams[2].nw3d2:b.cams[2].nd2:3==T?3==m&&3==q?b.cams[2].nl3w3d3:3==m?b.cams[2].nl3d3:3==q?b.cams[2].nw3d3:b.cams[2].nd3:4<=T?3==m?b.cams[2].nl3d4:b.cams[2].nd4:3==m&&3==q?b.cams[2].nl3w3:3==m?b.cams[2].nl3:3==q?b.cams[2].nw3:b.cams[2].n;
if(3==I)return 4==v&&4==m?b.cams[3].nl4c4:4==q?b.cams[3].nw4:4==v?b.cams[3].nc4:4==m?b.cams[3].nl4:b.cams[3].n;if(4==I)return 6==v?b.cams[4].nc6:5==m?b.cams[4].nl5:6==m?b.cams[4].nl6:b.cams[4].n;if(5==I)return b.cams[5].n;if(6==I)return 11==m&&11==q?b.cams[6].nl11w11:11==m?b.cams[6].nl11:11==v?b.cams[6].nc11:21==m?b.cams[6].nl21:11==q?b.cams[6].nw11:12==q?b.cams[6].nw12:21==q?b.cams[6].nw21:b.cams[6].n;if(7==I)return 10==v?b.cams[7].nc10:10==m?b.cams[7].nl10:b.cams[7].n;if(8==I)return b.cams[8].n;
if(9==I)return 26==q?b.cams[9].nw24:b.cams[9].n;if(10==I)return 20==q?b.cams[10].nw20:b.cams[10].n;if(11==I)return b.cams[11].n;if(12==I)return b.cams[12].n;if(13==I)return 16==q?b.cams[13].nw16:13==q?b.cams[13].nw13:13==v?b.cams[13].nc13:b.cams[13].n;if(14==I)return 14==q?b.cams[14].nw14:14==v?b.cams[14].nc14:b.cams[14].n;if(15==I)return 15==q?b.cams[15].nw15:b.cams[15].n}function of(){!ta&&Ac!=!ab&&Bc&&(Ac=!ab,ab&&(document.getElementById("fullscreen").style.display="block",ta=!0));var a=S();F++;
0==F%2&&(jb+=1);Fb=mb||na;for(var f=0;255>f;f++)Za[f]=pc[f]||Za[f];C.fillRect(0,0,1280,720);C.clearRect(0,0,1280,720);C.font="30px VT323";C.fillStyle="#000000";c.clearColor(0,0,0,1);c.clear(c.COLOR_BUFFER_BIT);d.reset();d.scale([1,-1]);if(0==K)if(d.push(),d.scale([1280,720]),c.bindTexture(c.TEXTURE_2D,Nc),B(O),d.pop(),a=Math.floor(a/300)%4,1>nb){var r=Math.floor(19*nb);Fc("Downloading Assets..","Downloading Assets"+".".repeat(a),660);La("["+"#".repeat(r)+" ".repeat(19-r)+"]",700)}else 2>nb?Fc("Extracting..",
"Extracting"+".".repeat(a),680):3==nb&&La("you eagler",700);else if(1==K){E(138,391,369,441)&&0!=U&&(U=0,A(n.camswitch,l.main));E(137,458,367,510)&&1!=U&&(U=1,A(n.camswitch,l.main));E(135,526,394,586)&&2!=U&&kb&&(U=2,A(n.camswitch,l.main));E(129,597,474,661)&&3!=U&&lb&&(U=3,A(n.camswitch,l.main));Ga[38]&&0<U&&(U--,A(n.camswitch,l.main));Ga[40]&&U<(kb?lb?3:2:1)&&(U++,A(n.camswitch,l.main));d.push();d.scale([1280,720]);c.bindTexture(c.TEXTURE_2D,b.title);B(O);d.pop();.03>Math.random()&&(d.push(),d.scale([1280,
720]),c.bindTexture(c.TEXTURE_2D,b.sstatic.scan[jb%7]),Vb(),Yb(.5),d.pop());Ta+=.1*Math.random()-.05;.5<Ta&&(Ta-=.01);.7<Ta&&(Ta=.7);.2>Ta&&(Ta=.2);d.push();d.scale([1280,720]);c.bindTexture(c.TEXTURE_2D,b.sstatic.norm[jb%6]);Yb(Ta);d.pop();r=0;kb&&(d.push(),d.translate([136,534]),d.scale([255,51]),c.bindTexture(c.TEXTURE_2D,b.title6th),B(O),d.pop(),r+=1);lb&&(d.push(),d.translate([134,604]),d.scale([340,50]),c.bindTexture(c.TEXTURE_2D,b.title7th),B(O),d.pop(),r+=1);Qb&&(r+=1);d.push();d.translate([134,
55]);d.scale([295,457]);c.bindTexture(c.TEXTURE_2D,2>r?b.titletext:b.titletext2);B(O);d.pop();1==U&&(d.push(),d.translate([152,505]),d.scale([72,18]),c.bindTexture(c.TEXTURE_2D,b.titlenight[Pb]),B(O),d.pop());d.push();1==U?d.translate([80,467]):2==U?d.translate([80,540]):3==U?d.translate([80,611]):d.translate([80,403]);d.scale([46,27]);c.bindTexture(c.TEXTURE_2D,b.titleselector);B(O);d.pop();d.push();d.translate([0,685]);d.scale([1280,35]);c.bindTexture(c.TEXTURE_2D,b.titlebottom);B(O);d.pop();d.push();
d.translate([980,0]);d.scale([300,70]);c.bindTexture(c.TEXTURE_2D,b.titletop);B(O);d.pop();d.push();c.bindTexture(c.TEXTURE_2D,b.titlestar);d.translate([148,278]);d.scale([80,80]);for(f=0;f<r;f++)B(O),d.translate([1.1,0]);d.pop();qc&&(na&&!E(200,50,1080,670)||Ga[27]?qc=!1:(C.fillStyle="#000000",C.fillRect(200,50,880,620),C.lineWidth=5,C.lineJoin="bevel",C.strokeStyle="#FFFFFF",C.strokeRect(200,50,880,620),C.fillStyle="#FFFFFF",C.font="40px VT323",La("Copyright Disclaimer",100),C.drawImage(b.copyinfo,
290,110,700,530)));na?0==U&&E(138,391,369,441)?(Jc(1),Z=1,ka(),A(n.camswitch,l.main),pa=F,K=2):1==U&&E(137,458,367,510)?(Z=Pb,ka(),A(n.camswitch,l.main),pa=F,K=2):2==U&&E(135,526,394,586)?(Z=6,ka(),A(n.camswitch,l.main),pa=F,K=2):3==U&&E(129,597,474,661)?K=7:E(460,686,704,719)?qc=!0:E(1010,0,1280,35)&&window.open("https://darviglet/","_blank"):Za[13]&&(0==U?(ka(),A(n.camswitch,l.main),pa=F,K=2):1==U?(ka(),A(n.camswitch,l.main),pa=F,K=2):2==U?(ka(),A(n.camswitch,l.main),pa=F,K=2):3==U&&(ka(),A(n.camswitch,
l.main),pa=F,K=2));Za[54]&&Za[57]&&(Z=8,ka(),A(n.camswitch,l.main),pa=F,K=2);DEBUG&&Ga[32]&&(ka(),P=7,X=a,K=6,A(n.sticknya,l.main))}else if(2==K)C.font="100px font",C.fillStyle="#FFFFFF",La("Night "+Z,300),C.font="60px font",C.fillStyle="#FFFFFF",La("12:00 AM",380),10>F-pa&&Ic(),70<F-pa&&(lf(),K=3);else if(3==K){r=f=!1;W||za?f=E(0,620,700,720)||E(0,710,1280,720):ib||(f=0!=ba&&69!=ba?E(0,620,930,720):E(0,620,1280,720));!W&&10<=F-Aa&&za&&(r=W=!0,Va=F);!Na&&f&&0==Q&&!Ca&&20<F-Aa?(Na=!0,Aa=F,W?(A(n.camclose,
l.main),W=!1,24==m?(Q=1,Ra=F,wb()):24==q?(Q=2,Ra=F,wb()):24==y?(Q=5,Ra=F,wb()):25==y&&(y=24)):A(n.camopen,l.main),za=!za):Na&&!E(0,620,1280,720)&&(Na=!1);6==T&&0==Q&&(da||xa?(A(n.laxdudecrash,l.main),Ya||(Sa-=10*gc),gc+=5,T=w(0,1),Da(3),qa=a,Cb=0):(Q=4,Ra=F,wb(),W&&(A(n.camclose,l.main),za=W=!1,Na=!0,Aa=F)));24==v&&0==Q&&(Q=3,Ra=F,wb(),W&&(A(n.camclose,l.main),za=W=!1,Na=!0,Aa=F));if(7E4<a-bc&&(bc=a,ma+=1,2!=ma&&3!=ma&&4!=ma||7==P||(ia+=1,ea+=1,aa+=1,la+=1,ha+=1),6<=ma&&(0==Q||7==Q))){X=a;Hc();A(n.nightend,
l.main);K=5;return}if(6E4<a-kc&&0==w(0,600)){kc=a;var J=n.random[w(0,1)],g=w(3,6),L=0;for(f=0;f<g;f++)setTimeout(function(){A(J,l.half)},L),L=0==w(0,1)?L+w(600,1E3):L+w(1500,5E3)}f=m;g=q;L=v;var p=T,ob=y;if(0==Q){if(4959<a-fc&&0==w(0,5)&&(fc=a,w(3,20)<ia||0!=Pa&&3<ma&&1==w(0,3))){var N=0==Pa&&ma>(1==P?3:2)||1==w(0,2);if(17==m&&11!=v)m=11,21==q&&(q=15),1==P&&0==ba&&(ba=1);else if(11==m||21==m){var h=w(1,5);if(1==h||2==h||N)m=3;3!=h&&4!=h||10==v||(m=10);5==h&&(m=21)}else if(3==m){h=w(1,3);if(a-Pa>=
6E3*(25-ia)||1==h||3==h||N)m=1;2==h&&4!=q&&(m=4)}else if(1==m){h=w(1,5);if(2==h||3==h||1==P&&0!=Pa)m=3;if(a-Pa>=4E3*(25-ia)||1==h||4==h||5==h)m=0}else if(0==m)da||xa?(Pa=a,m=0==w(0,2)?3:1):m=24;else if(4==m){h=w(1,5);if(1==h||2==h||5==h||N)m=3;3==h&&6!=v&&(m=5);4==h&&6!=v&&(m=6)}else if(5==m||6==m)h=w(1,8),1!=h&&2!=h&&3!=h&&4!=h&&!N||4==q||(m=4),5!=h&&6!=h||10==v||N||(m=10),7!=h||Jb||N||(m=18),8!=h||Bb||Ab||7==q||8==q||N||(m=7);else if(18==m)m=9;else if(9==m)Jb=!0,h=w(1,2),1==h&&(m=5),2==h&&(m=6),
6==v&&(v=10);else if(10==m){h=w(1,7);if(1==h||2==h||3==h||4==h||5==h)m=6;6!=h&&7!=h||11==q||21==q||11==v||(m=21)}else 7==m?m=19:19==m&&(Ab=!0,h=w(1,2),1==h&&(m=5),2==h&&(m=6),6==v&&(v=10))}if(4933<a-ec&&0==w(0,5)&&(ec=a,w(3,20)<ea))if(N=0==Pa&&ma>(1==P?3:2)||1==w(0,2),17==q&&11!=v)q=11,21==m&&(m=11);else if(11==q||21==q){h=w(1,7);if(1==h||2==h)q=14,14==v&&(v=13);if(3==h||4==h||N||a-Xa>=5E3*(25-ea))q=13,13==v&&(v=14);5==h&&(q=15);6==h&&(q=26);7==h&&(q=3)}else if(14==q){h=w(1,5);if(1==h||3==h||N||a-
Xa>=5E3*(25-ea))q=13,13==v&&(v=14);if(2==h||4==h)q=15;5==h&&11!=v&&11!=m&&21!=m&&(q=21)}else if(13==q){h=w(1,8);if(0==Xa||a-Xa>=4E3*(25-ea)||1==h||3==h||7==h||8==h||N)q=16;if(2==h||4==h)q=14,14==v&&(v=13);5==h&&11!=v&&11!=m&&21!=m&&(q=21);6==h&&2!=v&&(q=3)}else if(16==q)q=22;else if(22==q)q=23;else if(23==q)fa||xa?(Xa=a,q=13):q=24;else if(15==q){h=w(1,3);if(1==h||N||a-Xa>=7E3*(25-ea))q=14,14==v&&(v=13);2==h&&11!=v&&11!=m&&21!=m&&(q=21);3==h&&(q=26)}else if(26==q){h=w(1,3);if(1==h||2==h)q=15;3==h&&
(q=20)}else if(20==q)q=26;else if(3==q){h=w(1,2);if(2==h||N)q=13,13==v&&(v=14);1==h&&4!=m&&(q=4)}else 4==q?(h=w(1,2),1!=h&&!N||2==v||(q=3),2!=h||Bb||Ab||7==m||19==m||(q=7)):7==q?q=8:8==q&&4!=m&&(Bb=!0,q=4);if(4926<a-dc&&0==w(0,5)&&(dc=a,w(3,20)<aa))if(N=0==Oa&&ma>(1==P?3:2)||1==w(0,2),17==v&&11!=m&&11!=q&&21!=m&&21!=q)v=11,3==P&&0==ba&&(ba=3);else if(11==v)h=w(1,6),1!=h&&2!=h&&3!=h&&!N||3==q||(v=2),4!=h&&5!=h||10==m||(v=10),6==h&&(14!=q?v=14:13!=q&&16!=q&&(v=13));else if(10==v&&6!=m&&5!=m)v=6;else if(2==
v){h=w(1,4);if(1==h||2==h||N)v=1;3==h&&(v=4);4==h&&13!=q&&16!=q&&(v=13)}else if(4==v&&5!=m&&6!=m)v=!N&&1!=w(1,3)||3==q?6:2;else if(6==v){h=w(1,3);if(1==h||2==h||N||a-Oa>=9E3*(25-aa))v=4;3==h&&10!=m&&(v=10)}else if(10==v)h=w(1,3),1!=h&&2!=h||5==m||6==m||(v=6),3==h&&11!=m&&11!=q&&21!=m&&21!=q&&(v=11);else if(13==v)h=w(1,3),(2==h||3==h||N||a-Oa>=6E3*(25-aa))&&3!=y&&(v=2),1==h&&14!=q&&(v=14);else if(14==v)h=w(1,3),(2==h||3==h||N||a-Oa>=6E3*(25-aa))&&11!=m&&11!=q&&21!=m&&21!=q&&(v=11),1==h&&13!=q&&(v=
13);else if(1==v){h=w(1,2);if(1==h||0==Oa||a-Oa>=7E3*(25-aa))v=0;2==h&&(v=3!=q?2:0)}else 0==v&&1==w(0,7)&&(v=0==w(0,1)&&3!=q?2:1,Oa=a);if(4757<a-ic&&0==w(0,5)&&(ic=a,w(3,20)<ha))if(-1==y)y=6,6==P&&0==ba&&(ba=4);else if(0==y)da||xa?15E3<a-Lb&&(h=w(1,2),1==h&&(y=2),2==h&&(y=1),Wa=a):y=25;else if(1==y||2==y)a-Wa>=3E3*(25-ha)||0==w(0,3)?(h=w(1,2),1==h&&(y=0),2==h&&(y=13)):y=3;else if(3==y)y=a-Wa>=4E3*(25-ha)||0==w(0,3)?2:4;else if(4==y)y=a-Wa>=4E3*(25-ha)||0==w(0,1)?2:7;else if(6==y){h=w(1,11);if(1==
h||7==h||9==h)y=1;if(2==h||8==h||10==h)y=2;if(3==h||11==h)y=7;4==h&&(y=15);5==h&&(y=14);6==h&&(y=13)}else 7==y?(h=w(1,2),1==h&&(y=4),2==h&&(y=6)):15==y?y=14:14==y?y=13:13==y?y=a-Wa>=3500*(25-ha)||0==w(0,3)?22:2:22==y?y=23:23==y&&(fa||xa?15E3<a-Lb&&(y=13,Wa=a):y=25);6579<a-cc&&0==w(0,20)&&(cc=a,w(3,20)<la&&4>T&&(a-Kb>2E3+200*(20-la)?(T+=1,qa=a,W&&4==T&&0==I&&(Ea[0]=a+200,A(n.laxdudecart,l.main),T=5,qa=a,Va=F,Qa=!0),1==T&&0==w(0,2)&&A(n.toilet,l.main),2==T&&(A(n.deee,l.main),2==P&&0==ba&&(ba=2)),Da(3),
DEBUG&&console.log("lax + 1 > "+T)):Cb>2E4+1E3*(25-la)&&(T=4,qa=a,Da(3),W&&0==I&&(Ea[0]=a+200,A(n.laxdudecart,l.main),T=5,qa=a,Va=F,Qa=!0))));N=[];T!=p&&N.push(3);(!W||1!=I&&2!=I)&&a-Kb>w(1E3,1E4)&&(Cb=0);!W||1!=I&&2!=I||(Kb=a);4==T&&2E4<a-qa&&(T=5,DEBUG&&console.log("lax is here"),qa=a);5==T&&3E3<a-qa&&(T=6,DEBUG&&console.log("ur fucked"),qa=a);m!=f&&(N.push(m),Da(m),Da(f),DEBUG&&console.log("longarms: "+f+" > "+m));q!=g&&(N.push(q),Da(q),Da(g),DEBUG&&console.log("wierdclimber: "+g+" > "+q));v!=
L&&(N.push(v),gb=a,Da(v),Da(L),DEBUG&&console.log("charles: "+L+" > "+v));y!=ob&&(N.push(y),Lb=a,Ea[y]=Ba?a+w(100,200):a+w(3E3,4E3),-1!=ob&&(Ea[ob]=Ba?a+w(1E3,2E3):a+w(15E3,3E4)),DEBUG&&console.log("winston: "+ob+" > "+y));g={};for(f=0;f<N.length;g={$jscomp$loop$prop$finalpos$2:g.$jscomp$loop$prop$finalpos$2},f++)g.$jscomp$loop$prop$finalpos$2=N[f],setTimeout(function(rc){return function(){var sc=n.footsteps[w(0,5)],ja=zc[rc.$jscomp$loop$prop$finalpos$2];var $a=0==ja.length?[364,191]:ua[ja[0]];var Rb=
W?ua[I]:[366,212];ja=$a[0]-Rb[0];$a=$a[1]-Rb[1];ja=(280-Math.sqrt(ja*ja+$a*$a))/280;if(isNaN(ja)||.05>ja)ja=.05;1<ja&&(ja=1);Dc(sc,.5*ja,l.main)}}(g),w(1E3*f,1500*f+2E3));0<N.length&&a-Db>w(75E3,2E5)&&(Db=a,A(n.loud[w(0,4)],l.half));a-Db>w(15E4,3E5)&&(Db=a,2==v||0!=w(0,2)?A(n.loud[w(3,4)],l.main):A(n.loud[w(0,2)],l.half));((0==m||0==y)&&da||(23==q||23==y)&&fa)&&5E3<a-mc&&0==w(0,60)&&(mc=a,A(n.atdoor[w(0,2)],l.main));(22==q||22==y)&&0<a-lc&&(f=n.boilerroom[w(0,6)],lc=a+w(500,1500),A(f,l.half));25==
v&&a-gb>w(2E4,35E3)-600*aa&&(v=24,gb=a)}if(W&&0==Q){g=!1;if(1==I||2==I)Cb+=a-hc;!da&&!xa&&0==v&&a-gb>w(15E3,3E4)-600*aa&&(v=25,gb=a,Da(0),DEBUG&&console.log("charles is in"));M(l.office,.03);M(l.sstatic,Math.max(.07*(Ha-.17),0));if(na)for(f=0;18>f;f++)L=760+ua[f][0],p=325+ua[f][1],E(L,p,L+37,p+25)&&I!=f&&(A(n.camswitch,l.main),Va=F,I=f,g=!0);if(g||r)4==T&&0==I?(A(n.laxdudecart,l.main),T=5,qa=a,Qa=!0):Qa=!1;0<a-Ea[I]?(M(l.camglitch,0),17==I?(c.bindTexture(c.TEXTURE_2D,b.cams[17].n),r=640,f=r+360,f=
Math.abs((3*F+5464)%(2*f)-f)-180,0>f&&(f=0),f>r&&(f=r),d.push(),d.translate([-f,0]),d.scale([1920,720]),G.bind(),yb(.3,1),B(G),d.pop()):16==I?(c.bindTexture(c.TEXTURE_2D,b.cams[16].n),r=1280,f=r+360,f=Math.abs((3*F+43234)%(2*f)-f)-180,0>f&&(f=0),f>r&&(f=r),G.bind(),yb(.4,1),d.push(),d.translate([-f,0]),d.scale([2560,720]),B(G),d.pop(),d.push(),d.translate([1350-f,0]),d.scale([1210,720]),18==m?(c.bindTexture(c.TEXTURE_2D,b.cams[16].r.l18),B(G)):9==m?(c.bindTexture(c.TEXTURE_2D,b.cams[16].r.lt),B(G)):
Jb&&(c.bindTexture(c.TEXTURE_2D,b.cams[16].r.lf),B(G)),d.pop(),d.push(),d.translate([-f,0]),d.scale([1250,720]),7==m?(c.bindTexture(c.TEXTURE_2D,b.cams[16].l.l7),B(G)):19==m?(c.bindTexture(c.TEXTURE_2D,b.cams[16].l.lt),B(G)):Ab?(c.bindTexture(c.TEXTURE_2D,b.cams[16].l.wf),B(G)):7==q?(c.bindTexture(c.TEXTURE_2D,b.cams[16].l.w7),B(G)):8==q?(c.bindTexture(c.TEXTURE_2D,b.cams[16].l.lt),B(G)):Bb&&(c.bindTexture(c.TEXTURE_2D,b.cams[16].l.wf),B(G)),d.pop(),d.push(),d.translate([1645-f,0]),d.scale([280,370]),
G.bind(),yb(.4,280/720),4==m&&4==v?(c.bindTexture(c.TEXTURE_2D,b.cams[16].d.l4c4),B(G)):4==m?(c.bindTexture(c.TEXTURE_2D,b.cams[16].d.l4),B(G)):4==q&&(c.bindTexture(c.TEXTURE_2D,b.cams[16].d.w4),B(G)),d.pop()):0==I&&Qa?(r=F-Va,50>=r&&(10>=r?c.bindTexture(c.TEXTURE_2D,b.laxhall[0]):c.bindTexture(c.TEXTURE_2D,b.laxhall[Math.floor((r-10)/2)]),d.push(),d.scale([1280,720]),B(O),d.pop(),50<=r&&(Ea[0]=Ba?a+100:a+5E3,Qa=!1))):(d.push(),c.bindTexture(c.TEXTURE_2D,nf()),d.scale([1280,720]),B(O),d.pop()),y==
I&&(0==I?Ea[0]=a+1E3:(d.push(),c.bindTexture(c.TEXTURE_2D,b.winstedcam),d.scale([1280,720]),B(O),d.pop())),Ha+=.07*Math.random()-.035,.3<Ha&&(Ha-=.01),.5<Ha&&(Ha=.5),.15>Ha&&(Ha=.15),d.push(),d.scale([1280,720]),c.bindTexture(c.TEXTURE_2D,b.sstatic.norm[jb%6]),Yb(Ha),d.pop()):(M(l.camglitch,1),yc());d.push();d.scale([1280,720]);c.bindTexture(c.TEXTURE_2D,b.office.overlay);B(O);d.pop();0==Math.floor(F/20)%2&&(d.push(),d.translate([578,30]),d.scale([103,28]),c.bindTexture(c.TEXTURE_2D,b.office.rec),
B(O),d.pop());fb&&(E(900,0,1280,720)||E(0,600,1280,720))&&(fb=!1);fb||E(730,0,1280,720)||E(0,500,1280,720)||(fb=!0);if(fb){d.push();d.translate([1040,530]);for(f=0;18>f;f++)d.push(),r=ua[f],r=[.4*r[0],.4*r[1]],d.translate(r),d.scale([15,10]),f==I&&0==Math.floor(F/15)%2?Ib([.551,.68,0,1]):Ib([.258,.258,.258,1]),d.pop();d.push();d.scale([200,150]);c.bindTexture(c.TEXTURE_2D,b.office.cammap);Ec()}else{d.push();d.translate([760,325]);for(f=0;18>f;f++)d.push(),d.translate(ua[f]),d.scale([37,25]),f==I&&
0==Math.floor(F/15)%2?Ib([.551,.68,0,1]):Ib([.258,.258,.258,1]),d.pop();C.font="20px font";C.fillStyle="#FFFFFF";C.fillText(Oc[I],770,332);d.push();d.scale([500,375]);c.bindTexture(c.TEXTURE_2D,b.office.cammap);Vb()}B(O);d.pop();d.pop();10>F-Va&&Ic()}else{Ca?M(l.office,0):M(l.office,.1);M(l.sstatic,0);M(l.camglitch,0);Ca&&M(l.ambience,0);E(0,0,200,720)&&(R-=10);E(0,0,400,720)&&(R-=5);E(880,0,1280,720)&&(R+=5);E(1080,0,1280,720)&&(R+=10);na&&!Ca&&0==Q&&(E(64,492,118,566)?24==m||24==y||25==y?A(n.doorerr,
l.main):(A(n.door,l.main),da=!da,eb=F):E(1176,486,1217,572)&&(24==q||24==y||25==y?A(n.doorerr,l.main):(A(n.door,l.main),fa=!fa,db=F)),!E(61,320,90,370)||24!=m&&24!=y&&25!=y||A(n.doorerr,l.main),!E(1205,318,1231,369)||24!=q&&24!=y&&25!=y||A(n.doorerr,l.main));Fb&&!Ca&&0==Q?(E(61,320,90,370)&&24!=m&&24!=y&&25!=y?0==sa&&(0==y?(da||A(n.winston,l.main),sa=b.office.llights):0==m?(da||A(n.longarms,l.main),sa=b.office.llightl):sa=b.office.llight):sa=0,E(1205,318,1231,369)&&24!=q&&24!=y&&25!=y?0==ra&&(23==
y?(fa||A(n.winston,l.main),ra=b.office.rlights):23==q?(fa||A(n.weirdclimber,l.main),ra=b.office.rlightw):ra=b.office.rlight):ra=0):sa=ra=0;4==Q&&(R-=50);0>R&&(R=0);384<R&&(R=384);r=0;G.bind();yb(.3,1);if(0==Q)d.push(),d.translate([-R,0]),d.scale([1664,720]),c.bindTexture(c.TEXTURE_2D,b.office.normal),B(G),d.pop(),24==y&&(yb(.3,235/720),c.bindTexture(c.TEXTURE_2D,b.office.tablewinston),d.push(),d.translate([730-R,205]),d.scale([245,235]),B(G),d.pop()),8>F-eb?(da?c.bindTexture(c.TEXTURE_2D,b.office.ldoor[F-
eb]):c.bindTexture(c.TEXTURE_2D,b.office.ldoor[7-(F-eb)]),d.push(),d.translate([-R,0]),d.scale([375,720]),B(G),d.pop()):da?(0!=sa?(r=1,c.bindTexture(c.TEXTURE_2D,b.office.ldoor.l)):c.bindTexture(c.TEXTURE_2D,b.office.ldoor.d),d.push(),d.translate([-R,0]),d.scale([375,720]),B(G),d.pop()):0!=sa&&(r=1,d.push(),d.translate([-R,0]),d.scale([525,720]),c.bindTexture(c.TEXTURE_2D,sa),B(G),d.pop()),8>F-db?(fa?c.bindTexture(c.TEXTURE_2D,b.office.rdoor[F-db]):c.bindTexture(c.TEXTURE_2D,b.office.rdoor[7-(F-db)]),
d.push(),d.translate([1664-R-375,0]),d.scale([375,720]),B(G),d.pop()):fa?(0!=ra?(r=1,c.bindTexture(c.TEXTURE_2D,b.office.rdoor.l)):c.bindTexture(c.TEXTURE_2D,b.office.rdoor.d),d.push(),d.translate([1664-R-375,0]),d.scale([375,720]),B(G),d.pop()):0!=ra&&(r=1,d.push(),d.translate([1664-R-525,0]),d.scale([525,720]),c.bindTexture(c.TEXTURE_2D,ra),B(G),d.pop());else if(f=!1,g=F-Ra,1==Q?(c.bindTexture(c.TEXTURE_2D,b.office.js.longarms[g]),d.push(),d.scale([1280,720]),B(G),d.pop(),24<=g&&(f=!0)):2==Q?(c.bindTexture(c.TEXTURE_2D,
b.office.js.wierdclimber[9<g?9:g]),d.push(),d.scale([1280,720]),B(G),d.pop(),19<=g&&(f=!0)):3==Q?(d.push(),d.translate([-R,0]),d.scale([1664,720]),c.bindTexture(c.TEXTURE_2D,b.office.js.charles[g]),B(G),d.pop(),19<=g&&(f=!0),17>g&&(fa&&(c.bindTexture(c.TEXTURE_2D,b.office.rdoor.d),d.push(),d.translate([1664-R-375,0]),d.scale([375,720]),B(G),d.pop()),da&&(c.bindTexture(c.TEXTURE_2D,b.office.ldoor.d),d.push(),d.translate([-R,0]),d.scale([375,720]),B(G),d.pop()))):4==Q?(d.push(),d.translate([-R,0]),
d.scale([1664,720]),c.bindTexture(c.TEXTURE_2D,b.office.js.lax[g]),B(G),d.pop(),17<=g&&(f=!0),fa&&(c.bindTexture(c.TEXTURE_2D,b.office.rdoor.d),d.push(),d.translate([1664-R-375,0]),d.scale([375,720]),B(G),d.pop())):5==Q?(c.bindTexture(c.TEXTURE_2D,b.office.js.winston[g]),d.push(),d.scale([1280,720]),B(G),d.pop(),14<=g&&(f=!0)):6==Q?(c.bindTexture(c.TEXTURE_2D,b.office.js.winstondark[g]),d.push(),d.scale([1280,720]),B(O),d.pop(),15<=g&&(f=!0)):7==Q&&(0==oa&&5E3<a-X&&(oa=1,Mb=R,A(n.winstonsong,l.main)),
g=Mb-R,0>g&&(g=-g),L=50*g,2E4<L&&(L=2E4),1==oa&&a-X>39E3-L&&(oa=2,X=a,Mb=R,ka()),2==oa&&a-X>w(300,1E3)&&(oa=3),3==oa&&a-X>2E4-L-10*g&&(Q=6,Ra=F,ka(),wb()),g=!(2==oa&&0!=w(0,2)),3>oa&&g&&(c.bindTexture(c.TEXTURE_2D,b.office.dark1),d.push(),d.translate([-R,0]),d.scale([1664,720]),B(G),d.pop()),2==oa&&g?M(l.office,.05):M(l.office,0),1==oa&&0!=(F/2^3566)%3&&(yb(.3,150/720),c.bindTexture(c.TEXTURE_2D,b.office.dark2),d.push(),d.translate([173-R,100]),d.scale([110,150]),B(G),d.pop())),f){Hc();A(n.static1,
l.main);K=4;X=a;return}M(l.lights,r);ab&&1E4>a-xc&&(C.font="20px VT323",C.fillStyle="#FFFFFF",La("press F to enter fullscreen and hide this message",50));r=0==Q?F-Aa:2*(F-Aa)+3;if(10>r)za?c.bindTexture(c.TEXTURE_2D,b.office.cam_anim[r]):c.bindTexture(c.TEXTURE_2D,b.office.cam_anim[9-r]),d.push(),d.scale([1280,720]),B(O),d.pop();else if(!Ca&&0==Q){Na||(c.bindTexture(c.TEXTURE_2D,b.office.camzone),d.push(),d.translate([320,650]),d.scale([600,60]),B(O),d.pop());!Eb&&6E3<a-nc&&15E3>a-nc&&(1==P?(c.bindTexture(c.TEXTURE_2D,
b.skipcall),na&&E(10,10,110,45)&&(ma=2,ia+=1,ea+=1,Nb=a+1E3,Sa-=200,M(l.call,0),A(n.staticloop,l.main),Eb=!0)):(c.bindTexture(c.TEXTURE_2D,b.mutecall),na&&E(10,10,110,45)&&(M(l.call,0),Eb=!0)),d.push(),d.translate([10,10]),d.scale([100,35]),B(O),d.pop());if(0!=ba&&69!=ba)if(ib){if(c.bindTexture(c.TEXTURE_2D,1==ba?b.sticky1:2==ba?b.sticky2:3==ba?b.sticky3:b.sticky4),d.push(),d.translate([490,200]),d.scale([300,300]),B(O),d.pop(),Ga[27]||na&&!E(490,200,790,500)&&!E(1070,585,1280,720))ib=!1,ba=69}else c.bindTexture(c.TEXTURE_2D,
b.foundsticky),Vb(),d.push(),d.translate([1070,585]),d.scale([200,125]),Yb(Math.sin(F/5)/13+.6),d.pop(),Ec(),na&&E(1070,585,1280,720)&&(A(n.stickyopen,l.main),ib=!0);0>a-Nb&&yc()}Ia+=.1*Math.random()-.06;.001>Math.random()&&(Ia+=.7*Math.random()-.35);0>Ia&&(Ia=0);.3<Ia&&(Ia-=.2);1<Ia&&(Ia=1);d.push();d.scale([1280,720]);Ib([0,0,0,.3*Ia]);d.pop()}r=1;if(0!=sa||0!=ra)r+=1;fa&&(r+=1);da&&(r+=1);W&&(r+=1);if(2==P&&6E3<a-hb||3==P&&5E3<a-hb||4==P&&4E3<a-hb||5<=P&&3E3<a-hb&&!Ya)hb=a,--Sa;1E3<=a-jc&&!Ya&&
(jc=a,Sa-=r,5>=Sa&&!Ca&&(da&&(da=!1,eb=F,A(n.door,l.main)),fa&&(fa=!1,db=F,A(n.door,l.main)),W&&(Aa=F,W=za=!1),Ca=!0));0==Q&&(0>=Sa&&(Q=7,M(l.office,0),M(l.sstatic,0),M(l.camglitch,0),M(l.ambience,0),X=a,A(n.powerloss,l.main)),!ib&&100<a-Nb&&(f=Math.floor(Sa/10),C.font="40px font",C.fillStyle="#FFFFFF",0==ma?vc("12\u2002AM",40,65):vc(ma+"\u2002AM",40,65),C.font="20px font",vc("Night "+P,40,95),C.fillText("Power Left:   %",40,650),C.font="26.5px font",C.fillText(10>f?" "+f:f,177,650),C.font="20px font",
C.fillText("Usage:\u2008"+"#".repeat(r),40,680)));hc=a}else 4==K?1E4>a-X?yc():15E3>a-X?(c.bindTexture(c.TEXTURE_2D,b.death),d.push(),d.scale([1280,720]),B(O),d.pop()):(K=1,Ob()):5==K?(r=(a-X-2E3)/1E3,0>r&&(r=0),1<r&&(r=1),r*=150,C.fillStyle="#FFFFFF",C.font="150px font",La("5   ",410-r),La("6   ",560-r),La("  AM",410),C.fillStyle="#000000",C.fillRect(350,0,500,280),C.fillRect(350,410,500,305),1E4<a-X&&(5==P?(Kc(!0),X=a,K=6,A(n.sticknya,l.main)):6==P?(Lc(!0),X=a,K=6,A(n.sticknya,l.main)):7==P?(20!=
aa||20!=ia||20!=ea||20!=la||20!=ha||Ya||Ba||xa||Mc(!0),X=a,K=6,A(n.sticknya,l.main)):8==P?(K=1,Ob()):(Jc(P+1),Z=P+1,A(n.camswitch,l.main),pa=F,K=2))):6==K?(5==P&&c.bindTexture(c.TEXTURE_2D,b.check1),6==P&&c.bindTexture(c.TEXTURE_2D,b.check2),7==P&&c.bindTexture(c.TEXTURE_2D,b.check3),d.push(),d.scale([1280,720]),B(O),d.pop(),24500<a-X&&(ka(),K=1,Ob())):7==K&&(c.bindTexture(c.TEXTURE_2D,b.customnight),d.push(),d.scale([1280,720]),B(O),d.pop(),d.push(),d.translate([30,30]),d.scale([50,50]),c.bindTexture(c.TEXTURE_2D,
b.x),B(O),d.pop(),na&&(a=!0,E(48,419,97,483)?0<z.longarms&&--z.longarms:E(204,419,253,483)?20>z.longarms&&(z.longarms+=1):E(297,419,346,483)?0<z.wierdclimber&&--z.wierdclimber:E(453,419,502,483)?20>z.wierdclimber&&(z.wierdclimber+=1):E(549,419,598,483)?0<z.laxdude&&--z.laxdude:E(705,419,754,483)?20>z.laxdude&&(z.laxdude+=1):E(797,419,846,483)?0<z.charles&&--z.charles:E(953,419,1002,483)?20>z.charles&&(z.charles+=1):E(1042,419,1091,483)?0<z.winston&&--z.winston:E(1198,419,1247,483)?20>z.winston&&(z.winston+=
1):E(702,517,755,542)?z.infinitepower=!z.infinitepower:E(702,550,755,575)?z.reducedstatic=!z.reducedstatic:E(702,583,755,608)?z.noaggression=!z.noaggression:E(360,634,409,698)?(--Ua,0>Ua&&(Ua=Sb.length-1),z=JSON.parse(JSON.stringify(Sb[Ua]))):E(1199,634,1248,698)?(Ua+=1,Ua>Sb.length-1&&(Ua=0),z=JSON.parse(JSON.stringify(Sb[Ua]))):E(867,517,1249,620)?(a=!1,Z=7,ka(),A(n.camswitch,l.main),pa=F,K=2):E(30,30,80,80)?(a=!1,K=1):a=!1,a&&A(n.doorerr,l.main)),Ga[27]&&(K=1),C.fillStyle="#FFFFFF",C.font="60px font",
C.fillText(10>z.longarms?" "+z.longarms:z.longarms,116,477),C.fillText(10>z.wierdclimber?" "+z.wierdclimber:z.wierdclimber,364,477),C.fillText(10>z.laxdude?" "+z.laxdude:z.laxdude,612,477),C.fillText(10>z.charles?" "+z.charles:z.charles,863,477),C.fillText(10>z.winston?" "+z.winston:z.winston,1108,477),jf(z.name,780,409,684),C.font="30px font",z.infinitepower&&C.fillText("X",720,543),z.reducedstatic&&C.fillText("X",720,575),z.noaggression&&C.fillText("X",720,608));Ga[70]&&D();na=Fb=!1;for(f=0;255>
f;f++)Ga[f]=!1,Za[f]=!1;for(;(a=c.getError())!=c.NO_ERROR;)a==c.INVALID_ENUM?console.log("GL ERROR: INVALID_ENUM"):a==c.INVALID_VALUE?console.log("GL ERROR: INVALID_VALUE"):a==c.INVALID_OPERATION?console.log("GL ERROR: INVALID_OPERATION"):a==c.INVALID_FRAMEBUFFER_OPERATION?console.log("GL ERROR: INVALID_FRAMEBUFFER_OPERATION"):a==c.OUT_OF_MEMORY?console.log("GL ERROR: OUT_OF_MEMORY"):a==c.CONTEXT_LOST_WEBGL&&console.log("GL ERROR: CONTEXT_LOST_WEBGL")}var sb,tb,c,C,Y,Pc,Ja,Tb,Ub,ub,vb,va,wa,Cc,zb,
cb,wc,mb,Fb,na,ab,Ac,Bc,ta,pc,Za,Ga,bb,Nc,u,b,n,l,Hb,tc,Qc,Rc,Sc,Tc,Uc,O,ya,Ma,G,Zb,$b,nb,K,pb,F,d,Pb,Z,R,xc,da,fa,eb,db,W,za,Aa,Na,Va,I,ac,m,q,v,T,y,Pa,Xa,Oa,Wa,ia,ea,aa,la,ha,fb,Jb,Bb,Ab,ma,bc,P,X,fc,ec,dc,cc,Kb,gc,Cb,hc,Qa,ic,gb,qa,Lb,Q,Ra,sa,ra,Sa,Ca,jc,hb,kc,Db,lc,Mb,oa,mc,ba,ib,oc,Eb,nc,Nb,Ya,Ba,xa,Ua,Sb,z,Ta,Ha,jb,qc,ua,Oc,Ea,zc,qb,Fa,Ia,U,pa,kb,lb,Qb;return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress){sb=document.getElementById("webglcanvas");tb=document.getElementById("2dcanvas");
c=sb.getContext("webgl");C=tb.getContext("2d");C.imageSmoothingEnabled=!1;try{Pc=window.AudioContext||window.webkitAudioContext,Y=new Pc}catch(f){return alert("your browser does not support AudioContexts so yoo bad you can't play"),a["return"]()}Ja=Y.destination;if(!(c&&c instanceof WebGLRenderingContext))return alert("your browser does not support webgl so too bad you can't play"),a["return"]();Ub=Tb=1;wa=va=vb=ub=0;zb=Cc=!1;wc=cb=1;na=Fb=mb=!1;ab=!0;Bc=Ac=!1;ta=!0;pc=[];Za=[];Ga=[];window.addEventListener("resize",
k);window.addEventListener("mousemove",x);window.addEventListener("mousedown",function(){na=Fb=mb=Cc=!0;DEBUG&&console.log("[x: "+va+", y: "+wa+"]")});window.addEventListener("mouseup",function(){mb=(Cc=!1,zb)});window.addEventListener("keydown",function(f){pc[f.keyCode]=!0;Za[f.keyCode]=!0;Ga[f.keyCode]=!0});window.addEventListener("keyup",function(f){pc[f.keyCode]=!1});window.addEventListener("touchmove",function(f){ta||(x(f.touches[0]),cb=f.touches[0].radiusX,cb=f.touches[0].radiusY,f.preventDefault())});
window.addEventListener("touchstart",function(f){ta||(x(f.touches[0]),cb=f.touches[0].radiusX,cb=f.touches[0].radiusY,na=Fb=mb=zb=!0,f.preventDefault())});window.addEventListener("touchend",function(f){ta||(mb=zb=!1,f.preventDefault())});window.addEventListener("touchcancel",function(f){ta||(mb=zb=!1,f.preventDefault())});window.addEventListener("contextmenu",function(f){f.preventDefault();f.cancelBubble=!0;return!1});document.addEventListener("selectstart",function(f){f.preventDefault();return!1});
bb=[];return a.yield(t("smile.jpg"),2)}Nc=a.yieldResult;S();Xb.prototype.attribute=function(f){this.attributes[f]=c.getAttribLocation(this.id,f)};Xb.prototype.uniform=function(f){this.uniforms[f]=c.getUniformLocation(this.id,f)};Xb.prototype.bind=function(){c.useProgram(this.id)};u={};b={};n={};l={};Hb=c.createBuffer();c.bindBuffer(c.ARRAY_BUFFER,Hb);c.bufferData(c.ARRAY_BUFFER,new Float32Array([0,0,1,0,1,1,0,0,1,1,0,1]),c.STATIC_DRAW);tc=xb(c.VERTEX_SHADER,"#version 100\n #define multimatrix(mat1,mat2,vec) vec2(mat1.x*vec.x + mat1.y*vec.y + mat1.z, mat2.x*vec.x + mat2.y*vec.y + mat2.z)\n precision mediump float; attribute vec2 vert; varying vec2 uv; uniform vec3 matrixr1; uniform vec3 matrixr2; void main(){ uv = vert; gl_Position = vec4(vec2(-1,1) + multimatrix(matrixr1,matrixr2,vert) / vec2(640,360), 0, 1.0); }");
Qc=xb(c.FRAGMENT_SHADER,"#version 100\n precision mediump float; varying vec2 uv; uniform sampler2D tex; void main(){ gl_FragColor = texture2D(tex, uv); }");Rc=xb(c.FRAGMENT_SHADER,"#version 100\n precision mediump float; varying vec2 uv; uniform vec4 color; void main(){ gl_FragColor = color; }");Sc=xb(c.FRAGMENT_SHADER,"#version 100\n precision mediump float; varying vec2 uv; uniform float alpha; uniform sampler2D tex; void main(){ gl_FragColor = texture2D(tex, uv); gl_FragColor *= alpha; }");Tc=
xb(c.VERTEX_SHADER,"#version 100\n #define multimatrix(mat1,mat2,vec) vec2(mat1.x*vec.x + mat1.y*vec.y + mat1.z, mat2.x*vec.x + mat2.y*vec.y + mat2.z)\n precision mediump float; attribute vec2 vert; varying vec2 xy; varying vec2 uv; uniform vec3 matrixr1; uniform vec3 matrixr2; void main(){ vec2 eagler = vec2(-1,1) + multimatrix(matrixr1,matrixr2,vert) / vec2(640,360); xy = eagler; uv = vert; gl_Position = vec4(eagler, 0, 1.0); }");Uc=xb(c.FRAGMENT_SHADER,"#version 100\n precision mediump float; varying vec2 xy; varying vec2 uv; uniform sampler2D tex; uniform float warp; uniform float heightfac;  void main(){ float CurrentSinStep = xy.x / (2.0/3.1415) + 3.1415/2.0; float v = ((uv.y * heightfac) - xy.y * (((sin(CurrentSinStep) / (3.1415/2.0)) - 0.5) * warp - (warp/2.0/3.1415)))/heightfac; gl_FragColor = texture2D(tex, vec2(uv.x, v)); }");
O=Wb(tc,Qc);O.attribute("vert");O.uniform("matrixr1");O.uniform("matrixr2");O.uniform("tex");ya=Wb(tc,Sc);ya.attribute("vert");ya.uniform("matrixr1");ya.uniform("matrixr2");ya.uniform("tex");ya.uniform("alpha");Ma=Wb(tc,Rc);Ma.attribute("vert");Ma.uniform("matrixr1");Ma.uniform("matrixr2");Ma.uniform("color");G=Wb(Tc,Uc);G.attribute("vert");G.uniform("matrixr1");G.uniform("matrixr2");G.uniform("tex");G.uniform("warp");G.uniform("heightfac");Zb=.3;$b=1;G.bind();c.uniform1f(G.uniforms.warp,.3);c.uniform1f(G.uniforms.heightfac,
1);c.enable(c.BLEND);c.blendFunc(c.SRC_ALPHA,c.ONE_MINUS_SRC_ALPHA);K=nb=0;pb=new XMLHttpRequest;pb.responseType="arraybuffer";pb.addEventListener("progress",function(f){nb=f.loaded/f.total});pb.addEventListener("load",function(f){nb=1;untar(pb.response).progress(function(r){u[r.name]={buffer:r.buffer,url:r.getBlobUrl()}}).then(function(r){function J(e,ca){return $jscomp.asyncExecutePromiseGeneratorProgram(function(rb){return rb["return"](t(u["img/cams/cam"+e+ca+".jpg"].url))})}function g(e,ca,rb){var Gb,
Vc;return $jscomp.asyncExecutePromiseGeneratorProgram(function(uc){if(1==uc.nextAddress)return Gb=b.cams[e],Vc="n"+rb,uc.yield(t(u["img/cams/cam"+ca+rb+".jpg"].url),2);Gb[Vc]=uc.yieldResult;uc.jumpToEnd()})}function L(){function e(){var rb=n.glitch[w(0,3)],Gb=Y.createBufferSource();Gb.buffer=rb;Gb.connect(l.camglitch);setTimeout(e,Math.floor(1E3*rb.duration));Gb.start()}e();l.ambience=Y.createGain();M(l.ambience,.2);l.ambience.connect(Ja);l.lights=Y.createGain();M(l.lights,0);l.lights.connect(Ja);
var ca=Y.createBufferSource();ca.buffer=n.lights;ca.loop=!0;ca.connect(l.lights);ca.start();l.office=Y.createGain();M(l.office,0);l.office.connect(Ja);ca=Y.createBufferSource();ca.buffer=n.office;ca.loop=!0;ca.connect(l.office);ca.start();l.sstatic=Y.createGain();M(l.sstatic,0);l.sstatic.connect(Ja);ca=Y.createBufferSource();ca.buffer=n.staticloop;ca.loop=!0;ca.connect(l.sstatic);ca.start()}var p,ob,N,h,rc,sc,ja,$a,Rb,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,
wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){switch(e.nextAddress){case 1:b.sstatic={},b.sstatic.norm=[],b.sstatic.scan=[],b.sstatic.heavyscan=[],p=0;case 2:if(!(6>p)){e.jumpTo(4);break}ob=b.sstatic.norm;N=p;return e.yield(t(u["img/ui/static/norm/"+
p+".jpg"].url),5);case 5:ob[N]=e.yieldResult;p++;e.jumpTo(2);break;case 4:p=0;case 6:if(!(7>p)){e.jumpTo(8);break}h=b.sstatic.scan;rc=p;return e.yield(t(u["img/ui/static/scan/"+p+".png"].url),9);case 9:h[rc]=e.yieldResult;p++;e.jumpTo(6);break;case 8:p=0;case 10:if(!(5>p))return $a=b,e.yield(t(u["img/ui/title.jpg"].url),14);sc=b.sstatic.heavyscan;ja=p;return e.yield(t(u["img/ui/static/heavyscan/"+p+".png"].url),13);case 13:sc[ja]=e.yieldResult;p++;e.jumpTo(10);break;case 14:return $a.title=e.yieldResult,
Rb=b,e.yield(t(u["img/ui/titletext.png"].url),15);case 15:return Rb.titletext=e.yieldResult,Wc=b,e.yield(t(u["img/ui/titletext2.png"].url),16);case 16:Wc.titletext2=e.yieldResult,b.titlenight=[],p=1;case 17:if(!(5>=p))return Zc=b,e.yield(t(u["img/ui/6thnight.png"].url),21);Xc=b.titlenight;Yc=p;return e.yield(t(u["img/ui/night"+p+".png"].url),20);case 20:Xc[Yc]=e.yieldResult;p++;e.jumpTo(17);break;case 21:return Zc.title6th=e.yieldResult,$c=b,e.yield(t(u["img/ui/7thnight.png"].url),22);case 22:return $c.title7th=
e.yieldResult,ad=b,e.yield(t(u["img/ui/bottom.png"].url),23);case 23:return ad.titlebottom=e.yieldResult,bd=b,e.yield(t(u["img/ui/top.png"].url),24);case 24:return bd.titletop=e.yieldResult,cd=b,e.yield(t(u["img/ui/winston.png"].url),25);case 25:return cd.titlestar=e.yieldResult,dd=b,e.yield(t(u["img/ui/selector.png"].url),26);case 26:return dd.titleselector=e.yieldResult,ed=b,e.yield(t(u["img/ui/sticky1.jpg"].url),27);case 27:return ed.sticky1=e.yieldResult,fd=b,e.yield(t(u["img/ui/sticky2.jpg"].url),
28);case 28:return fd.sticky2=e.yieldResult,gd=b,e.yield(t(u["img/ui/sticky3.jpg"].url),29);case 29:return gd.sticky3=e.yieldResult,hd=b,e.yield(t(u["img/ui/sticky4.jpg"].url),30);case 30:return hd.sticky4=e.yieldResult,id=b,e.yield(t(u["img/ui/sticky4.jpg"].url),31);case 31:return id.sticky4=e.yieldResult,jd=b,e.yield(t(u["img/ui/foundsticky.png"].url),32);case 32:return jd.foundsticky=e.yieldResult,kd=b,e.yield(t(u["img/ui/skipcall.png"].url),33);case 33:return kd.skipcall=e.yieldResult,ld=b,e.yield(t(u["img/ui/mutecall.png"].url),
34);case 34:return ld.mutecall=e.yieldResult,md=b,e.yield(t(u["img/ui/custom.jpg"].url),35);case 35:return md.customnight=e.yieldResult,nd=b,e.yield(t(u["img/ui/x.png"].url),36);case 36:return nd.x=e.yieldResult,od=b,e.yield(t(u["img/ui/check1.jpg"].url),37);case 37:return od.check1=e.yieldResult,pd=b,e.yield(t(u["img/ui/check2.jpg"].url),38);case 38:return pd.check2=e.yieldResult,qd=b,e.yield(t(u["img/ui/check3.jpg"].url),39);case 39:return qd.check3=e.yieldResult,rd=b,e.yield(t(u["img/ui/death.jpg"].url),
40);case 40:return rd.death=e.yieldResult,b.office={},sd=b.office,e.yield(t(u["img/office/normal.jpg"].url),41);case 41:return sd.normal=e.yieldResult,td=b.office,e.yield(t(u["img/office/dark1.jpg"].url),42);case 42:return td.dark1=e.yieldResult,ud=b.office,e.yield(t(u["img/office/dark2.jpg"].url),43);case 43:return ud.dark2=e.yieldResult,vd=b.office,e.yield(t(u["img/office/llight.jpg"].url),44);case 44:return vd.llight=e.yieldResult,wd=b.office,e.yield(t(u["img/office/llightl.jpg"].url),45);case 45:return wd.llightl=
e.yieldResult,xd=b.office,e.yield(t(u["img/office/llights.jpg"].url),46);case 46:return xd.llights=e.yieldResult,yd=b.office,e.yield(t(u["img/office/rlight.jpg"].url),47);case 47:return yd.rlight=e.yieldResult,zd=b.office,e.yield(t(u["img/office/rlightw.jpg"].url),48);case 48:return zd.rlightw=e.yieldResult,Ad=b.office,e.yield(t(u["img/office/rlights.jpg"].url),49);case 49:return Ad.rlights=e.yieldResult,Bd=b.office,e.yield(t(u["img/office/winston.jpg"].url),50);case 50:Bd.tablewinston=e.yieldResult,
b.office.ldoor=[],p=0;case 51:if(!(8>p)){e.jumpTo(53);break}Cd=b.office.ldoor;Dd=p;return e.yield(t(u["img/office/dl"+p+".jpg"].url),54);case 54:Cd[Dd]=e.yieldResult;p++;e.jumpTo(51);break;case 53:b.office.rdoor=[],p=0;case 55:if(!(8>p))return Gd=b.office.ldoor,e.yield(t(u["img/office/dld.jpg"].url),59);Ed=b.office.rdoor;Fd=p;return e.yield(t(u["img/office/dr"+p+".jpg"].url),58);case 58:Ed[Fd]=e.yieldResult;p++;e.jumpTo(55);break;case 59:return Gd.d=e.yieldResult,Hd=b.office.ldoor,e.yield(t(u["img/office/dll.jpg"].url),
60);case 60:return Hd.l=e.yieldResult,Id=b.office.rdoor,e.yield(t(u["img/office/drd.jpg"].url),61);case 61:return Id.d=e.yieldResult,Jd=b.office.rdoor,e.yield(t(u["img/office/drl.jpg"].url),62);case 62:return Jd.l=e.yieldResult,Kd=b.office,e.yield(t(u["img/ui/camflip.png"].url),63);case 63:return Kd.camzone=e.yieldResult,Ld=b.office,e.yield(t(u["img/ui/map.png"].url),64);case 64:return Ld.cammap=e.yieldResult,Md=b.office,e.yield(t(u["img/ui/overlay.png"].url),65);case 65:return Md.overlay=e.yieldResult,
Nd=b.office,e.yield(t(u["img/ui/rec.png"].url),66);case 66:Nd.rec=e.yieldResult,b.office.cam_anim=[],p=0;case 67:if(!(10>p)){e.jumpTo(69);break}Od=b.office.cam_anim;Pd=p;return e.yield(t(u["img/ui/cam"+p+".png"].url),70);case 70:Od[Pd]=e.yieldResult;p++;e.jumpTo(67);break;case 69:b.office.js={},b.office.js.longarms=[],p=0;case 71:if(!(25>p)){e.jumpTo(73);break}Qd=b.office.js.longarms;Rd=p;return e.yield(t(u["img/office/jscares/l"+p+".jpg"].url),74);case 74:Qd[Rd]=e.yieldResult;p++;e.jumpTo(71);break;
case 73:b.office.js.wierdclimber=[],p=0;case 75:if(!(10>p)){e.jumpTo(77);break}Sd=b.office.js.wierdclimber;Td=p;return e.yield(t(u["img/office/jscares/w"+p+".jpg"].url),78);case 78:Sd[Td]=e.yieldResult;p++;e.jumpTo(75);break;case 77:b.office.js.charles=[],p=0;case 79:if(!(20>p)){e.jumpTo(81);break}Ud=b.office.js.charles;Vd=p;return e.yield(t(u["img/office/jscares/c"+p+".jpg"].url),82);case 82:Ud[Vd]=e.yieldResult;p++;e.jumpTo(79);break;case 81:b.office.js.lax=[],p=0;case 83:if(!(18>p)){e.jumpTo(85);
break}Wd=b.office.js.lax;Xd=p;return e.yield(t(u["img/office/jscares/d"+p+".jpg"].url),86);case 86:Wd[Xd]=e.yieldResult;p++;e.jumpTo(83);break;case 85:b.office.js.winston=[],p=0;case 87:if(!(15>p)){e.jumpTo(89);break}Yd=b.office.js.winston;Zd=p;return e.yield(t(u["img/office/jscares/s"+p+".jpg"].url),90);case 90:Yd[Zd]=e.yieldResult;p++;e.jumpTo(87);break;case 89:b.office.js.winstondark=[],p=0;case 91:if(!(16>p)){e.jumpTo(93);break}$d=b.office.js.winstondark;ae=p;return e.yield(t(u["img/office/jscares/s2"+
p+".jpg"].url),94);case 94:$d[ae]=e.yieldResult;p++;e.jumpTo(91);break;case 93:b.laxhall=[],p=0;case 95:if(!(21>p))return de=b,e.yield(t(u["img/cams/winston.png"].url),99);be=b.laxhall;ce=p;return e.yield(t(u["img/cams/laxdude/"+p+".jpg"].url),98);case 98:be[ce]=e.yieldResult;p++;e.jumpTo(95);break;case 99:return de.winstedcam=e.yieldResult,b.cams=[],b.cams[0]={},g(0,"00",""),g(0,"00","c0"),g(0,"00","c1"),g(0,"00","l1"),g(0,"00","l1c0"),g(0,"00","l1c1"),b.cams[1]={},g(1,"01",""),g(1,"01","c2"),g(1,
"01","c2d2"),g(1,"01","c2d3"),g(1,"01","c2d4"),g(1,"01","d2"),g(1,"01","d3"),g(1,"01","d4"),g(1,"01","l3"),g(1,"01","l3c2"),g(1,"01","l3c2d2"),g(1,"01","l3c2d3"),g(1,"01","l3c2d4"),g(1,"01","l3d2"),g(1,"01","l3d3"),g(1,"01","l3d4"),g(1,"01","l3w3"),g(1,"01","w3d3"),b.cams[2]={},g(2,"02",""),g(2,"02","d1"),g(2,"02","d2"),g(2,"02","d3"),g(2,"02","d4"),g(2,"02","l3"),g(2,"02","l3d1"),g(2,"02","l3d2"),g(2,"02","l3d3"),g(2,"02","l3d4"),g(2,"02","l3w3"),g(2,"02","l3w3d1"),g(2,"02","l3w3d3"),g(2,"02","w3"),
g(2,"02","w3d1"),g(2,"02","w3d2"),g(2,"02","w3d3"),b.cams[3]={},g(3,"03",""),g(3,"03","c4"),g(3,"03","l4"),g(3,"03","l4c4"),g(3,"03","w4"),b.cams[4]={},g(4,"04",""),g(4,"04","c6"),g(4,"04","l5"),g(4,"04","l6"),b.cams[5]={},g(5,"05",""),b.cams[6]={},g(6,"06",""),g(6,"06","c11"),g(6,"06","l11"),g(6,"06","l11w11"),g(6,"06","l21"),g(6,"06","w11"),g(6,"06","w12"),g(6,"06","w21"),b.cams[7]={},g(7,"07",""),g(7,"07","c10"),g(7,"07","l10"),b.cams[8]={},g(8,"08",""),b.cams[9]={},g(9,"09",""),g(9,"09","w24"),
b.cams[10]={},g(10,"10",""),g(10,"10","w20"),b.cams[11]={},g(11,"11",""),b.cams[12]={},g(12,"12",""),b.cams[13]={},g(13,"13",""),g(13,"13","c13"),g(13,"13","w13"),g(13,"13","w16"),b.cams[14]={},g(14,"14",""),g(14,"14","c14"),g(14,"14","w14"),b.cams[15]={},g(15,"15",""),g(15,"15","w15"),b.cams[16]={},b.cams[16].d={},b.cams[16].l={},b.cams[16].r={},ee=b.cams[16],e.yield(J("16",""),100);case 100:return ee.n=e.yieldResult,fe=b.cams[16].d,e.yield(J("16","dl4"),101);case 101:return fe.l4=e.yieldResult,
ge=b.cams[16].d,e.yield(J("16","dl4c4"),102);case 102:return ge.l4c4=e.yieldResult,he=b.cams[16].d,e.yield(J("16","dw4"),103);case 103:return he.w4=e.yieldResult,ie=b.cams[16].l,e.yield(J("16","ll7"),104);case 104:return ie.l7=e.yieldResult,je=b.cams[16].l,e.yield(J("16","llt"),105);case 105:return je.lt=e.yieldResult,ke=b.cams[16].l,e.yield(J("16","llf"),106);case 106:return ke.lf=e.yieldResult,le=b.cams[16].l,e.yield(J("16","lw7"),107);case 107:return le.w7=e.yieldResult,me=b.cams[16].l,e.yield(J("16",
"lwt"),108);case 108:return me.wt=e.yieldResult,ne=b.cams[16].l,e.yield(J("16","lwf"),109);case 109:return ne.wf=e.yieldResult,oe=b.cams[16].r,e.yield(J("16","rl18"),110);case 110:return oe.l18=e.yieldResult,pe=b.cams[16].r,e.yield(J("16","rlt"),111);case 111:return pe.lt=e.yieldResult,qe=b.cams[16].r,e.yield(J("16","rlf"),112);case 112:return qe.lf=e.yieldResult,b.cams[17]={},g(17,"17",""),n.amb=[],re=n.amb,e.yield(H(u["sounds/amb1.mp3"].buffer),113);case 113:return re[0]=e.yieldResult,se=n.amb,
e.yield(H(u["sounds/amb2.mp3"].buffer),114);case 114:return se[1]=e.yieldResult,te=n.amb,e.yield(H(u["sounds/amb3.mp3"].buffer),115);case 115:return te[2]=e.yieldResult,ue=n,e.yield(H(u["sounds/title.mp3"].buffer),116);case 116:return ue.title=e.yieldResult,ve=n,e.yield(H(u["sounds/nightend.mp3"].buffer),117);case 117:return ve.nightend=e.yieldResult,we=n,e.yield(H(u["sounds/static1.mp3"].buffer),118);case 118:return we.static1=e.yieldResult,xe=n,e.yield(H(u["sounds/static2.mp3"].buffer),119);case 119:return xe.static2=
e.yieldResult,ye=n,e.yield(H(u["sounds/camopen.mp3"].buffer),120);case 120:return ye.camopen=e.yieldResult,ze=n,e.yield(H(u["sounds/camclose.mp3"].buffer),121);case 121:return ze.camclose=e.yieldResult,Ae=n,e.yield(H(u["sounds/camswitch.mp3"].buffer),122);case 122:return Ae.camswitch=e.yieldResult,Be=n,e.yield(H(u["sounds/lights.wav"].buffer),123);case 123:return Be.lights=e.yieldResult,Ce=n,e.yield(H(u["sounds/office.wav"].buffer),124);case 124:return Ce.office=e.yieldResult,De=n,e.yield(H(u["sounds/staticloop.wav"].buffer),
125);case 125:return De.staticloop=e.yieldResult,Ee=n,e.yield(H(u["sounds/door.mp3"].buffer),126);case 126:return Ee.door=e.yieldResult,Fe=n,e.yield(H(u["sounds/deee.mp3"].buffer),127);case 127:return Fe.deee=e.yieldResult,Ge=n,e.yield(H(u["sounds/toilet.mp3"].buffer),128);case 128:return Ge.toilet=e.yieldResult,He=n,e.yield(H(u["sounds/yee2.mp3"].buffer),129);case 129:return He.doorerr=e.yieldResult,Ie=n,e.yield(H(u["sounds/powerloss.mp3"].buffer),130);case 130:return Ie.powerloss=e.yieldResult,
Je=n,e.yield(H(u["sounds/stick_n_ya2.mp3"].buffer),131);case 131:Je.sticknya=e.yieldResult,n.footsteps=[],p=0;case 132:if(!(6>p)){e.jumpTo(134);break}Ke=n.footsteps;Le=p;return e.yield(H(u["sounds/moving"+(p+1)+".mp3"].buffer),135);case 135:Ke[Le]=e.yieldResult;p++;e.jumpTo(132);break;case 134:n.boilerroom=[],p=0;case 136:if(!(7>p)){e.jumpTo(138);break}Me=n.boilerroom;Ne=p;return e.yield(H(u["sounds/boiler"+(p+1)+".mp3"].buffer),139);case 139:Me[Ne]=e.yieldResult;p++;e.jumpTo(136);break;case 138:n.random=
[],p=0;case 140:if(!(2>p)){e.jumpTo(142);break}Oe=n.random;Pe=p;return e.yield(H(u["sounds/random"+(p+1)+".mp3"].buffer),143);case 143:Oe[Pe]=e.yieldResult;p++;e.jumpTo(140);break;case 142:n.loud=[],p=0;case 144:if(!(5>p)){e.jumpTo(146);break}Qe=n.loud;Re=p;return e.yield(H(u["sounds/loud"+(p+1)+".mp3"].buffer),147);case 147:Qe[Re]=e.yieldResult;p++;e.jumpTo(144);break;case 146:n.atdoor=[],p=0;case 148:if(!(3>p))return Ue=n,e.yield(H(u["sounds/scream.mp3"].buffer),152);Se=n.atdoor;Te=p;return e.yield(H(u["sounds/atdoor"+
(p+1)+".mp3"].buffer),151);case 151:Se[Te]=e.yieldResult;p++;e.jumpTo(148);break;case 152:Ue.scream=e.yieldResult,n.call=[],p=0;case 153:if(!(7>p))return Xe=n,e.yield(H(u["sounds/heyDude.mp3"].buffer),157);Ve=n.call;We=p;return e.yield(H(u["sounds/phonecall"+(p+1)+".mp3"].buffer),156);case 156:Ve[We]=e.yieldResult;p++;e.jumpTo(153);break;case 157:return Xe.longarms=e.yieldResult,Ye=n,e.yield(H(u["sounds/eagler.mp3"].buffer),158);case 158:return Ye.weirdclimber=e.yieldResult,Ze=n,e.yield(H(u["sounds/yee3.mp3"].buffer),
159);case 159:return Ze.winston=e.yieldResult,$e=n,e.yield(H(u["sounds/cart.mp3"].buffer),160);case 160:return $e.laxdudecart=e.yieldResult,af=n,e.yield(H(u["sounds/crash.mp3"].buffer),161);case 161:return af.laxdudecrash=e.yieldResult,bf=n,e.yield(H(u["sounds/winstonsong.mp3"].buffer),162);case 162:return bf.winstonsong=e.yieldResult,cf=n,e.yield(H(u["sounds/stickyopen.mp3"].buffer),163);case 163:cf.stickyopen=e.yieldResult,n.glitch=[],p=0;case 164:if(!(4>p))return l.main=Ja,l.mute=Y.createGain(),
M(l.mute,0),l.mute.connect(Ja),l.half=Y.createGain(),M(l.half,.5),l.half.connect(Ja),l.camglitch=Y.createGain(),M(l.camglitch,0),l.camglitch.connect(Ja),l.call=Y.createGain(),M(l.call,1),l.call.connect(Ja),ff='<svg xmlns="http://www.w3.org/2000/svg" width="700" height="500"><foreignObject width="100%" height="100%"><body xmlns="http://www.w3.org/1999/xhtml" style="font-size:14px;color:white;"><div style="font-family:monospace;">'+decodeURIComponent(escape(String.fromCharCode.apply(null,new Uint8Array(u["copydisclaimermarkup.txt"].buffer))))+
"</div></body></foreignObject></svg>",gf=b,e.yield(V("data:image/svg+xml,"+encodeURIComponent(ff)),168);df=n.glitch;ef=p;return e.yield(H(u["sounds/glitch"+(p+1)+".mp3"].buffer),167);case 167:df[ef]=e.yieldResult;p++;e.jumpTo(164);break;case 168:gf.copyinfo=e.yieldResult,kf()?(alert("five nights at winston's works on mobile but is near impossible to play on most devices"),ta=Bc=!0,document.getElementById("mobilebutton").style.display="block",document.getElementById("allowsound").addEventListener("click",
function(){D();A(n.camopen,l.main);L();document.getElementById("mobilebutton").style.display="none";setTimeout(function(){ta=!1;K=1},1E3);Ob()}),document.getElementById("enterfull").addEventListener("click",function(){setTimeout(function(){ta=!1},1E3);D();document.getElementById("fullscreen").style.display="none"}),document.getElementById("hidefull").addEventListener("click",function(){setTimeout(function(){ta=!1},1E3);document.getElementById("fullscreen").style.display="none"})):(L(),K=1,setTimeout(function(){ta=
!1},1E3),Ob()),e.jumpToEnd()}})})});pb.open("GET","assets.tar",!0);pb.send();k();F=100;d={state:[1,0,0,0,1,0],stack:[],push:function(){d.stack.push(d.state)},pop:function(){d.state=d.stack.pop();d.state||d.loadIdentity()},reset:function(){d.loadIdentity();d.stack=[]},loadIdentity:function(){d.state=[1,0,0,0,1,0]},multiplyVec2:function(f){return[d.state[0]*f[0]+d.state[1]*f[1]+d.state[2],d.state[3]*f[0]+d.state[4]*f[1]+d.state[5]]},multiplyMat2:function(f){return[d.state[0]*f[0]+d.state[1]*f[3],d.state[0]*
f[1]+d.state[1]*f[4],d.state[0]*f[2]+d.state[1]*f[5]+d.state[2],d.state[3]*f[0]+d.state[4]*f[3],d.state[3]*f[1]+d.state[4]*f[4],d.state[3]*f[2]+d.state[4]*f[5]+d.state[5]]},translate:function(f){d.state=d.multiplyMat2([1,0,f[0],0,1,f[1]])},rotate:function(f){f*=.0174533;d.state=d.multiplyMat2([Math.cos(f),Math.sin(f),0,-Math.sin(f),Math.cos(f),0])},scale:function(f){d.state=d.multiplyMat2([f[0],0,0,0,f[1],0])},exportTo:function(f){c.uniform3f(f.uniforms.matrixr1,d.state[0],d.state[1],d.state[2]);
c.uniform3f(f.uniforms.matrixr2,d.state[3],d.state[4],d.state[5])}};Z=Pb=1;R=0;xc=S();fa=da=!1;db=eb=0;za=W=!1;Aa=0;Na=!1;ac=I=Va=0;v=q=m=17;T=0;y=-1;Wa=Oa=Xa=Pa=0;ia=3;ea=2;ha=la=aa=0;Ab=Bb=Jb=fb=!1;ma=0;bc=S();P=Z;cc=dc=ec=fc=X=0;Kb=S()+5E3;gc=2;Cb=0;hc=S();Qa=!1;gb=ic=0;qa=S();ra=sa=Ra=Q=Lb=0;Sa=999;Ca=!1;jc=S();hb=S();kc=S();Db=S();lc=S();oa=Mb=0;mc=S();ba=0;ib=!1;oc=1;Eb=!0;nc=S();Nb=0;xa=Ba=Ya=!1;Ua=-1;Sb=[{name:"3rd star",longarms:20,wierdclimber:20,laxdude:20,charles:20,winston:20,infinitepower:!1,
reducedstatic:!1,noaggression:!1},{name:"deevile",longarms:15,wierdclimber:15,laxdude:15,charles:15,winston:15,infinitepower:!1,reducedstatic:!0,noaggression:!1},{name:"darvy's mode",longarms:20,wierdclimber:20,laxdude:20,charles:20,winston:20,infinitepower:!0,reducedstatic:!0,noaggression:!0},{name:"classic fnaw",longarms:8,wierdclimber:8,laxdude:15,charles:0,winston:0,infinitepower:!1,reducedstatic:!0,noaggression:!1},{name:"yee challenge",longarms:5,wierdclimber:5,laxdude:5,charles:5,winston:5,
infinitepower:!1,reducedstatic:!0,noaggression:!1},{name:"eee challenge",longarms:10,wierdclimber:10,laxdude:10,charles:10,winston:10,infinitepower:!1,reducedstatic:!1,noaggression:!1},{name:"69420 mode",longarms:6,wierdclimber:9,laxdude:4,charles:2,winston:0,infinitepower:!0,reducedstatic:!0,noaggression:!1},{name:"darvy's other mode",longarms:20,wierdclimber:20,laxdude:20,charles:20,winston:20,infinitepower:!0,reducedstatic:!0,noaggression:!1},{name:"yeet",longarms:0,wierdclimber:5,laxdude:20,charles:0,
winston:0,infinitepower:!1,reducedstatic:!1,noaggression:!0}];z={name:"you eagler",longarms:6,wierdclimber:9,laxdude:4,charles:2,winston:0,infinitepower:!1,reducedstatic:!0,noaggression:!1};Ta=.6;Ha=.3;jb=69;qc=!1;ua=[[363,236],[266,246],[224,228],[170,210],[141,255],[5,228],[231,136],[117,133],[4,125],[231,54],[181,35],[136,15],[5,38],[351,175],[308,98],[342,61],[106,218],[98,38]];Oc="A Hall - Camera 1;Main Enterance - Camera 1;Main Enterance - Camera 2;A Hall - Camera 4;Pasillo 2 - Camera 1;A Hall - Camera 7;Main Hall - Camera 3;B Hall - Camera 2;B Hall - Camera 3;C Hall - Camera 1;C Hall - Camera 2;Pasillo 2 - Camera 2;C Hall - Camera 5;Lower Gym - Camera 1;Upper Gym - Camera 1;Fitness Center - Camera 1;A Hall - Camera 6;C Hall - Camera 4".split(";");
Ea=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];zc=[[0],[0],[1],[2,1],[3,16],[4],[4],[16],[16],[16],[7],[6],[6],[13],[14],[15],[13],[6],[16],[16],[10],[6],[],[],[],[],[9]];for(qb=0;qb<ua.length;qb++)ua[qb][0]*=1.25,ua[qb][1]*=1.25;Fa="fnaw1_";Ia=.5;pa=U=0;Qb=lb=kb=!1;mf();kb="1"==window.localStorage.getItem(Fa+"6th");Kc(kb);lb="1"==window.localStorage.getItem(Fa+"7th");Lc(lb);Qb="1"==window.localStorage.getItem(Fa+"20mode");Mc(Qb);setInterval(of,frameTime);a.jumpToEnd()})});